<!-- Добавление цитаты -->
<h2>Добавить цитату</h2>

<div class="row-fluid add-quote">

  <div class="span12 ">

    <form id="add-quote-form" class="module">

      <div class="h add-quote-success alert alert-success ">
        <a class="close"  href="#">&times;</a>
        <span>Цитата, успешно добавлена</span>
      </div>



      <div class="h add-quote-error alert alert-error ">
        <a class="close"  href="#">&times;</a>
        <span>Цитата не добавлена, произошла ошибка</span>
      </div>

      <div>
        <label for="add_quote">Цитата: </label>
        <textarea  id="add_quote" name="add_quote"></textarea>
      </div>

      <div>
        <label for="add_author">Автор: </label>
        <input type="text" id="add_author" name="add_author">
      </div>

      <div>
        <input class="btn" id="add-quote-btn" type="submit" value="Добавить">
      </div>
    </form>

  </div>
</div>