<div class="navbar">
	<div class="navbar-inner">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		       <span class="icon-bar"></span>
		       <span class="icon-bar"></span>
		       <span class="icon-bar"></span>
		    </a>
		    <a class="brand" href="#">Цитабаза</a>
		    <div class="nav-collapse collapse">
			    <ul class="nav">
					<li class="index-link nav-link"><a href="/">Главная</a></li>
					<li class="addQuote-link nav-link"><a href="#add-quote">Добавить цитату</a></li>
					<li class="quoteBase-link citabase-link nav-link"><a href="#citabase">База цитат</a></li>
					<li class="about-link  nav-link"><a href="#about">О приложении</a></li>
				</ul>
		    </div>
		    <span class="slogan help-inline">Разреши своим любимым цитатам напоминать о себе каждый день</span>
		    <!-- <span class="slogan help-inline">Уютное место для твоих любимых цитат</span> -->
		    <div class="sidebar fr">	
				<div class="profile-block">
					<span class="profile-heading">Профиль</span>
					<span class="profile-name "></span>
					<button class="btn logout-btn">Выйти</button>
					<div class="nclear"></div>
				</div>
		    </div>
	 </div>
</div>
