<h2>Забыли пароль?</h2>

<p class="lead">Введите свой email и мы пришлем вам письмо с дальнейшими инструкциями.</p>

<form class="forget-form" action="">
	<fieldset class="control-group ">
	  <label class="control-label" for="email">Email:</label>
	  <div class="controls">
	    <input name="email" type="text" id="email">
	  </div>
	</fieldset>
	<fieldset class="">
		<button type="submit" class="forget-btn btn disabled" disabled="disabled">Выслать письмо</button>
	</fieldset>
</form>	



<div id="forget-pass-popup" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h5>Письмо с инструкциями выслано на указанную вами почту.</h5>
  </div>
  <div class="modal-footer">
  </div>
</div>