<div class="navbar">
	<div class="navbar-inner">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		       <span class="icon-bar"></span>
		       <span class="icon-bar"></span>
		       <span class="icon-bar"></span>
		    </a>
		    <a class="brand" href="#">Цитабаза</a>
		    <div class="nav-collapse collapse">
				<ul class="nav">
					<li class="index-link active nav-link"><a href="/">Главная</a></li>
					<li class="registration-link nav-link"><a href="#registration">Регистрация</a></li>
					<li class="about-link  nav-link"><a href="#about">О приложении</a></li>
			    </ul>
		    </div>
		    <span class="slogan help-inline">Разреши своим любимым цитатам напоминать о себе каждый день</span>
		    <!-- <span class="slogan help-inline">Уютное место для твоих любимых цитат</span> -->
		    <div class="sidebar fr">					 
				<div class="login">
					<form class="login-form form-inline"  method="post" action="" >
						<a class="reg-link" href="#forget-pass">Забыли пароль ?</a>
						<span class="control-group ">
							<input class="input-medium" name="username" id="login-name" type="text" placeholder="Введите свое имя…"> 
						</span>							
						<label class="control-label" for="login-name"></label>
						<span class="control-group ">
							<input class="input-medium" name="password" id="login-password" type="password" placeholder="Введите пароль…">
						</span>
						<label class="control-label" for="login-password"></label>	
						<button type="submit"  class="login-send btn disabled" disabled="disabled" >Войти</button>
						<div class="nclear"></div>
					</form>
				</div>
		    </div>
	 </div>
</div>
