<h2>Хотите восстановить свой пароль?</h2>

<p class="lead">Введите свой новый пароль и подтвердите его.</p>

<form class="recovery-pass-form" action="">
	<fieldset class="control-group ">
	  <label class="control-label" for="email">Email:</label>
	  <div class="controls">
	    <input name="email" type="text" id="email">
	  </div>
	</fieldset>
	<fieldset class="control-group ">
	  <label class="control-label" for="password">Пароль:</label>
	  <div class="controls">
	    <input name="password" type="password" id="password">
	  </div>
	</fieldset>
	<fieldset class="control-group ">
	  <label class="control-label" for="passwordConfirmation">Подтверждение пароля:</label>
	  <div class="controls">
	    <input name="passwordConfirmation" type="password" id="passwordConfirmation">
	  </div>
	</fieldset>
	<fieldset class="">
		<button type="submit" class="recover-btn btn disabled" disabled="disabled">Сменить пароль</button>
	</fieldset>
</form>	


<div id="recover-pass-popup" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h5>Ваш новый пароль выслан на указанную вами почту. Вы можете авторизоваться используя его.</h5>
  </div>
  <div class="modal-footer">
  </div>
</div>